name: Create update develop pull request
on:
  push:
    branches: ['release/jm/**']
jobs:
  updateDevelop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: Reset branch
        run: |
          git fetch origin ${{ steps.extract_branch.outputs.branch }}:${{ steps.extract_branch.outputs.branch }}
          git reset --hard ${{ steps.extract_branch.outputs.branch }}
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v6
        with:
          branch: feature/jm/temp-auto-pr
      - name: Set reviewer if needed
        uses: hkusu/review-assign-action@v1
        with:
          assignees: rkolchakov
          reviewers: rkolchakov