name: Create update develop pull request
on:
  push:
    branches:
      - '*' 
jobs:
  updateDevelop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: Reset branch
        run: |
          git fetch origin steps.extract_branch.outputs.branch:steps.extract_branch.outputs.branch
          git reset --hard steps.extract_branch.outputs.branch
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: feature/jm/pr-from-test-branch